# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = python_beginner_tutorial
SUB_SRC_FILES = \
    preface.xml \
    python_beginner_tutorial.xml \
    ch01_python_intro.xml \
    ch02_python_download.xml \
    ch03_python_install.xml \
    ch04_python_dev_env.xml \
    ch05_python_grammar_and_basics.xml \
    ch06_python_learn_method.xml \
    ch07_python_faq.xml \
    ch08_python_res.xml \
    reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk